// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_Video ContentType = 0
	ContentType_Image ContentType = 1
	ContentType_Audio ContentType = 2
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "Video",
		1: "Image",
		2: "Audio",
	}
	ContentType_value = map[string]int32{
		"Video": 0,
		"Image": 1,
		"Audio": 2,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type VideoExt int32

const (
	VideoExt_mp4 VideoExt = 0
)

// Enum value maps for VideoExt.
var (
	VideoExt_name = map[int32]string{
		0: "mp4",
	}
	VideoExt_value = map[string]int32{
		"mp4": 0,
	}
)

func (x VideoExt) Enum() *VideoExt {
	p := new(VideoExt)
	*p = x
	return p
}

func (x VideoExt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoExt) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (VideoExt) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x VideoExt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoExt.Descriptor instead.
func (VideoExt) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

type ImageExt int32

const (
	ImageExt_jpeg ImageExt = 0
	ImageExt_png  ImageExt = 1
	ImageExt_bmp  ImageExt = 2
)

// Enum value maps for ImageExt.
var (
	ImageExt_name = map[int32]string{
		0: "jpeg",
		1: "png",
		2: "bmp",
	}
	ImageExt_value = map[string]int32{
		"jpeg": 0,
		"png":  1,
		"bmp":  2,
	}
)

func (x ImageExt) Enum() *ImageExt {
	p := new(ImageExt)
	*p = x
	return p
}

func (x ImageExt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageExt) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (ImageExt) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x ImageExt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageExt.Descriptor instead.
func (ImageExt) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

type AudioExt int32

const (
	AudioExt_mp3 AudioExt = 0
	AudioExt_wav AudioExt = 1
)

// Enum value maps for AudioExt.
var (
	AudioExt_name = map[int32]string{
		0: "mp3",
		1: "wav",
	}
	AudioExt_value = map[string]int32{
		"mp3": 0,
		"wav": 1,
	}
)

func (x AudioExt) Enum() *AudioExt {
	p := new(AudioExt)
	*p = x
	return p
}

func (x AudioExt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioExt) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[3].Descriptor()
}

func (AudioExt) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[3]
}

func (x AudioExt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioExt.Descriptor instead.
func (AudioExt) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x2e, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x10, 0x02, 0x2a,
	0x13, 0x0a, 0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x45, 0x78, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x6d,
	0x70, 0x34, 0x10, 0x00, 0x2a, 0x26, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x78, 0x74,
	0x12, 0x08, 0x0a, 0x04, 0x6a, 0x70, 0x65, 0x67, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x70, 0x6e,
	0x67, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x62, 0x6d, 0x70, 0x10, 0x02, 0x2a, 0x1c, 0x0a, 0x08,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x78, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x6d, 0x70, 0x33, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x77, 0x61, 0x76, 0x10, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_message_proto_goTypes = []interface{}{
	(ContentType)(0), // 0: ContentType
	(VideoExt)(0),    // 1: VideoExt
	(ImageExt)(0),    // 2: ImageExt
	(AudioExt)(0),    // 3: AudioExt
}
var file_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
