// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresignPutObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId     uint64      `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ObjKey      string      `protobuf:"bytes,2,opt,name=obj_key,json=objKey,proto3" json:"obj_key,omitempty"`
	ContentType ContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=ContentType" json:"content_type,omitempty"`
	// Types that are assignable to FileExt:
	//
	//	*PresignPutObjectRequest_VideoExt
	//	*PresignPutObjectRequest_ImageExt
	//	*PresignPutObjectRequest_AudioExt
	FileExt isPresignPutObjectRequest_FileExt `protobuf_oneof:"file_ext"`
}

func (x *PresignPutObjectRequest) Reset() {
	*x = PresignPutObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresignPutObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignPutObjectRequest) ProtoMessage() {}

func (x *PresignPutObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignPutObjectRequest.ProtoReflect.Descriptor instead.
func (*PresignPutObjectRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0}
}

func (x *PresignPutObjectRequest) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *PresignPutObjectRequest) GetObjKey() string {
	if x != nil {
		return x.ObjKey
	}
	return ""
}

func (x *PresignPutObjectRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_Video
}

func (m *PresignPutObjectRequest) GetFileExt() isPresignPutObjectRequest_FileExt {
	if m != nil {
		return m.FileExt
	}
	return nil
}

func (x *PresignPutObjectRequest) GetVideoExt() VideoExt {
	if x, ok := x.GetFileExt().(*PresignPutObjectRequest_VideoExt); ok {
		return x.VideoExt
	}
	return VideoExt_mp4
}

func (x *PresignPutObjectRequest) GetImageExt() ImageExt {
	if x, ok := x.GetFileExt().(*PresignPutObjectRequest_ImageExt); ok {
		return x.ImageExt
	}
	return ImageExt_jpeg
}

func (x *PresignPutObjectRequest) GetAudioExt() AudioExt {
	if x, ok := x.GetFileExt().(*PresignPutObjectRequest_AudioExt); ok {
		return x.AudioExt
	}
	return AudioExt_mp3
}

type isPresignPutObjectRequest_FileExt interface {
	isPresignPutObjectRequest_FileExt()
}

type PresignPutObjectRequest_VideoExt struct {
	VideoExt VideoExt `protobuf:"varint,4,opt,name=video_ext,json=videoExt,proto3,enum=VideoExt,oneof"`
}

type PresignPutObjectRequest_ImageExt struct {
	ImageExt ImageExt `protobuf:"varint,5,opt,name=image_ext,json=imageExt,proto3,enum=ImageExt,oneof"`
}

type PresignPutObjectRequest_AudioExt struct {
	AudioExt AudioExt `protobuf:"varint,6,opt,name=audio_ext,json=audioExt,proto3,enum=AudioExt,oneof"`
}

func (*PresignPutObjectRequest_VideoExt) isPresignPutObjectRequest_FileExt() {}

func (*PresignPutObjectRequest_ImageExt) isPresignPutObjectRequest_FileExt() {}

func (*PresignPutObjectRequest_AudioExt) isPresignPutObjectRequest_FileExt() {}

var File_request_proto protoreflect.FileDescriptor

var file_request_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88,
	0x02, 0x0a, 0x17, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x4b, 0x65, 0x79, 0x12, 0x2f,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x28, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x09, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x45, 0x78, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x45, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x45, 0x78, 0x74, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x45, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x65, 0x78, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x78,
	0x74, 0x48, 0x00, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x78, 0x74, 0x42, 0x0a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x78, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_request_proto_rawDescOnce sync.Once
	file_request_proto_rawDescData = file_request_proto_rawDesc
)

func file_request_proto_rawDescGZIP() []byte {
	file_request_proto_rawDescOnce.Do(func() {
		file_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_request_proto_rawDescData)
	})
	return file_request_proto_rawDescData
}

var file_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_proto_goTypes = []interface{}{
	(*PresignPutObjectRequest)(nil), // 0: PresignPutObjectRequest
	(ContentType)(0),                // 1: ContentType
	(VideoExt)(0),                   // 2: VideoExt
	(ImageExt)(0),                   // 3: ImageExt
	(AudioExt)(0),                   // 4: AudioExt
}
var file_request_proto_depIdxs = []int32{
	1, // 0: PresignPutObjectRequest.content_type:type_name -> ContentType
	2, // 1: PresignPutObjectRequest.video_ext:type_name -> VideoExt
	3, // 2: PresignPutObjectRequest.image_ext:type_name -> ImageExt
	4, // 3: PresignPutObjectRequest.audio_ext:type_name -> AudioExt
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_request_proto_init() }
func file_request_proto_init() {
	if File_request_proto != nil {
		return
	}
	file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresignPutObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PresignPutObjectRequest_VideoExt)(nil),
		(*PresignPutObjectRequest_ImageExt)(nil),
		(*PresignPutObjectRequest_AudioExt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_proto_goTypes,
		DependencyIndexes: file_request_proto_depIdxs,
		MessageInfos:      file_request_proto_msgTypes,
	}.Build()
	File_request_proto = out.File
	file_request_proto_rawDesc = nil
	file_request_proto_goTypes = nil
	file_request_proto_depIdxs = nil
}
